# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /
collections_dir:  collections
collections:
  main_pages:
    output: true
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "main_pages"
    values:
      icon: icon.svg
      image: image.jpeg
      layout: base_page

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.1

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
